### ISSUE TITLE
V1.2.5 testing checklist

### ISSUE THREAD

**Issue by KadenZipfel** [protofire/omen-exchange#1773]
Focus should primarily be on testing xDai tight integration. Can do various generic testing via the relay, e.g. market buy/sell.
Copy/paste this checklist into a comment below and check off what you've tested. 

- [x] Relay
    - [x] Enable
    - [x] Deposit
    - [x] Withdraw
    - [x] Generic market interactions (see above checklist)
        - [x] Transaction modal works as expected
            - [x] Correct block explorer links
            - [x] Tweet functionality
- [x] History tab transaction overview works as expected
- [x] Correct reality links on xDai
- [x] List view does not display scalar market current probability as undefined if no liquidity
- [x] Market scale works as expected if value out of bounds
    - [x] > upper bound
    - [ ] < lower bound
- [x] Buy button not disabled if 0 < amount < 0.01
- [x] Scalar markets not displaying as invalid if final outcome exactly 50%
- [ ] Redeem on xDai
    - [ ] Proper amount of winnings displayed
    - [ ] Scalar market winnings displayed before condition resolution
    - [ ] Redeeming works as expected
- [x] Max sell works as expected
- [ ] Wallet connection modal works as expected
    - [ ] Metamask
    - [ ] Walletconnect

**Comment by hexyls** [comment]
- [ ] Relay
    - [x] Enable
    - [x] Deposit
    - [ ] Withdraw
    - [ ] Generic market interactions (see above checklist)
        - [ ] Transaction modal works as expected
            - [ ] Correct block explorer links
            - [ ] Tweet functionality
- [ ] History tab transaction overview works as expected
- [ ] Correct reality links on xDai
- [ ] List view does not display scalar market current probability as undefined if no liquidity
- [ ] Market scale works as expected if value out of bounds
    - [ ] > upper bound
    - [ ] < lower bound
- [ ] Buy button not disabled if 0 < amount < 0.01
- [ ] Scalar markets not displaying as invalid if final outcome exactly 50%
- [ ] Redeem on xDai
    - [ ] Proper amount of winnings displayed
    - [ ] Scalar market winnings displayed before condition resolution
    - [ ] Redeeming works as expected
- [ ] Max sell works as expected
- [ ] Wallet connection modal works as expected
    - [ ] Metamask
    - [ ] Walletconnect

**Comment by pimato** [comment]
- [ ] Relay
    - [ ] Enable
    - [ ] Deposit
    - [ ] Withdraw
    - [ ] Generic market interactions (see above checklist)
        - [ ] Transaction modal works as expected
            - [ ] Correct block explorer links
            - [ ] Tweet functionality
- [ ] History tab transaction overview works as expected
- [ ] Correct reality links on xDai
- [ ] List view does not display scalar market current probability as undefined if no liquidity
- [ ] Market scale works as expected if value out of bounds
    - [ ] > upper bound
    - [ ] < lower bound
- [ ] Buy button not disabled if 0 < amount < 0.01
- [ ] Scalar markets not displaying as invalid if final outcome exactly 50%
- [ ] Redeem on xDai
    - [ ] Proper amount of winnings displayed
    - [ ] Scalar market winnings displayed before condition resolution
    - [ ] Redeeming works as expected
- [ ] Max sell works as expected
- [ ] Wallet connection modal works as expected
    - [ ] Metamask
    - [ ] Walletconnect

**Comment by Mi-Lan** [comment]
- [ ] Relay
    - [ ] Enable
    - [ ] Deposit
    - [ ] Withdraw
    - [ ] Generic market interactions (see above checklist)
        - [ ] Transaction modal works as expected
            - [ ] Correct block explorer links
            - [ ] Tweet functionality
- [ ] History tab transaction overview works as expected
- [ ] Correct reality links on xDai
- [ ] List view does not display scalar market current probability as undefined if no liquidity
- [ ] Market scale works as expected if value out of bounds
    - [ ] > upper bound
    - [ ] < lower bound
- [ ] Buy button not disabled if 0 < amount < 0.01
- [ ] Scalar markets not displaying as invalid if final outcome exactly 50%
- [ ] Redeem on xDai
    - [ ] Proper amount of winnings displayed
    - [ ] Scalar market winnings displayed before condition resolution
    - [ ] Redeeming works as expected
- [ ] Max sell works as expected
- [ ] Wallet connection modal works as expected
    - [ ] Metamask
    - [ ] Walletconnect

**Comment by pimato** [comment]
Hey @hexyls @KadenZipfel,

looks like we have a bug on the redeem process for scalar markets? The Omen UI told me to redeem my winnings:
<img width="615" alt="Bildschirmfoto 2021-03-26 um 12 06 51" src="https://user-images.githubusercontent.com/5337809/112626793-fb435380-8e30-11eb-9c1f-b7928d612430.png">

This is my xDai gnosis-safe:
https://blockscout.com/poa/xdai/address/0x224f2aec2650cd9Fa63b6E18C321F44069c8F4d5/token-transfers

This is the transaction which let me received `23.723522791848698067 WXDAI` :
https://blockscout.com/xdai/mainnet/tx/0x4e218dffd8ae070088b632a45e7fc6bb67d244e12ddb06f41765f8764e9c7912/token-transfers

**Comment by hexyls** [comment]
Had a look and that last tx looks ok and correct, it can only happen if you are logged in with your xdai wallet (not relay).

But that `23.72` reward one is confusing 🤔 is this related to https://github.com/protofire/omen-exchange/pull/1785 @KadenZipfel  ?

**Comment by pimato** [comment]
- Scalar
    - Buy from xDai network directly
    - Buy from mainnet <> xDai relay
    - Buy both directly and from mainnet <> xDai relay
- Categorical
    - Buy from xDai network directly
    - Buy from mainnet <> xDai relay
Resolve:
<img width="611" alt="Bildschirmfoto 2021-03-29 um 09 03 25" src="https://user-images.githubusercontent.com/5337809/112799122-38e0f000-906e-11eb-801e-05dded96c382.png">
Redeem:
<img width="611" alt="Bildschirmfoto 2021-03-29 um 09 05 36" src="https://user-images.githubusercontent.com/5337809/112799138-3ed6d100-906e-11eb-9722-7b01e92a15f7.png">
Correct Amount redeemed: 

- [ ] [Blockscout](https://blockscout.com/xdai/mainnet/tx/0x76f9e25e4d6ca9215f59c387288c0e88f77b687facc2aba4505a35accbf03704/token-transfers)

    - Buy both directly and from mainnet <> xDai relay

**Comment by pimato** [comment]
# Scalar

## Buy from xDai network directly
## Buy from mainnet <> xDai relay
## Buy both directly and from mainnet <> xDai relay
