### ISSUE TITLE
V1.2.6 testing checklist

### ISSUE THREAD

**Issue by KadenZipfel** [protofire/omen-exchange#1862]
Copy/paste this checklist into a comment below and check off what you've tested.

- [ ] Walletconnect
    - [ ] iPhone
    - [ ] Android
    - [ ] Test with various wallets
- [ ] Mainnet/xDai market detection
    - [ ] Incognito browser/no wallet connected
        - [ ] Mainnet market works
        - [ ] xDai market works
    - [ ] Metamask connected to mainnet
        - [ ] Mainnet market works
        - [ ] xDai market works
    - [ ] Metamask connected to xDai
        - [ ] Mainnet market works
        - [ ] xDai market works
- [ ] Scalar compound integration
    - [ ] Create market
        - [ ] Test with USDC
    - [ ] Add liquidity
    - [ ] Remove liquidity
    - [ ] Buy
    - [ ] Sell
    - [ ] Redeem
        - [ ] Correct amounts
- [ ] Meta data
    - [ ] Works as expected (proper title, description, image)
- [ ] Redeem
    - [ ] Correct amount of shares to redeem
        - [ ] Before and after resolving
    - [ ] Correct value of shares to redeem
        - [ ] Before and after resolving
    - [ ] Redeeming works as expected
- [ ] xDai <> Dai bridge
    - [ ] xDai => Dai batch claim works
- [ ] Unwrapping redeem positions
    - [ ] Scalar compound market unwraps cDai to Dai when redeeming
    - [ ] wxDai unwrapped to xDai on redeem

**Comment by pimato** [comment]
- [ ] Walletconnect
    - [ ] iPhone
    - [ ] Android
    - [ ] Test with various wallets
- [ ] Mainnet/xDai market detection
    - [ ] Incognito browser/no wallet connected
        - [ ] Mainnet market works
        - [ ] xDai market works
    - [ ] Metamask connected to mainnet
        - [ ] Mainnet market works
        - [ ] xDai market works
    - [ ] Metamask connected to xDai
        - [ ] Mainnet market works
        - [ ] xDai market works
- [ ] Scalar compound integration
    - [ ] Create market
        - [ ] Test with USDC
    - [ ] Add liquidity
    - [ ] Remove liquidity
    - [ ] Buy
    - [ ] Sell
    - [ ] Redeem
        - [ ] Correct amounts
- [ ] Meta data
    - [ ] Works as expected (proper title, description, image)
- [ ] Redeem
    - [ ] Correct amount of shares to redeem
        - [ ] Before and after resolving
    - [ ] Correct value of shares to redeem
        - [ ] Before and after resolving
    - [ ] Redeeming works as expected
- [ ] xDai <> Dai bridge
    - [ ] xDai => Dai batch claim works
- [ ] Unwrapping redeem positions
    - [ ] Scalar compound market unwraps cDai to Dai when redeeming
    - [ ] wxDai unwrapped to xDai on redeem

**Comment by hexyls** [comment]
- [x] Walletconnect
    - [x] iPhone
    - [ ] Android
    - [x] Test with various wallets
- [ ] Mainnet/xDai market detection
    - [x] Incognito browser/no wallet connected
        - [x] Mainnet market works
        - [x] xDai market works
    - [x] Metamask connected to mainnet
        - [x] Mainnet market works
        - [x] xDai market works
    - [x] Metamask connected to xDai
        - [ ] Mainnet market works
        - [ ] xDai market works
- [x] Scalar compound integration
    - [x] Create market
        - [ ] Test with USDC
    - [ ] Add liquidity
    - [ ] Remove liquidity
    - [ ] Buy
    - [ ] Sell
    - [ ] Redeem
        - [ ] Correct amounts
- [ ] Meta data
    - [ ] Works as expected (proper title, description, image)
- [ ] Redeem
    - [ ] Correct amount of shares to redeem
        - [ ] Before and after resolving
    - [ ] Correct value of shares to redeem
        - [ ] Before and after resolving
    - [ ] Redeeming works as expected
- [ ] xDai <> Dai bridge
    - [ ] xDai => Dai batch claim works
- [ ] Unwrapping redeem positions
    - [ ] Scalar compound market unwraps cDai to Dai when redeeming
    - [ ] wxDai unwrapped to xDai on redeem

**Comment by 0xVenky** [comment]
- [x] Walletconnect
    - [ ] iPhone
    - [ ] Android
    - [ ] Test with various wallets
- [ ] Mainnet/xDai market detection
    - [ ] Incognito browser/no wallet connected
        - [ ] Mainnet market works
        - [ ] xDai market works
    - [ ] Metamask connected to mainnet
        - [ ] Mainnet market works
        - [ ] xDai market works
    - [ ] Metamask connected to xDai
        - [ ] Mainnet market works
        - [ ] xDai market works
- [ ] Scalar compound integration
    - [ ] Create market
        - [ ] Test with USDC
    - [ ] Add liquidity
    - [ ] Remove liquidity
    - [ ] Buy
    - [ ] Sell
    - [ ] Redeem
        - [ ] Correct amounts
- [ ] Meta data
    - [ ] Works as expected (proper title, description, image)
- [ ] Redeem
    - [ ] Correct amount of shares to redeem
        - [ ] Before and after resolving
    - [ ] Correct value of shares to redeem
        - [ ] Before and after resolving
    - [ ] Redeeming works as expected
- [ ] xDai <> Dai bridge
    - [ ] xDai => Dai batch claim works
- [ ] Unwrapping redeem positions
    - [ ] Scalar compound market unwraps cDai to Dai when redeeming
    - [ ] wxDai unwrapped to xDai on redeem

**Comment by skyminert** [comment]
> Copy/paste this checklist into a comment below and check off what you've tested.
> 
> * [ ]  Walletconnect
>   
>   * [ ]  iPhone
>   * [ ]  Android
>   * [ ]  Test with various wallets
> * [ ]  Mainnet/xDai market detection
>   
>   * [ ]  Incognito browser/no wallet connected
>     
>     * [ ]  Mainnet market works
>     * [ ]  xDai market works
>   * [ ]  Metamask connected to mainnet
>     
>     * [ ]  Mainnet market works
>     * [ ]  xDai market works
>   * [ ]  Metamask connected to xDai
>     
>     * [ ]  Mainnet market works
>     * [ ]  xDai market works
> * [ ]  Scalar compound integration
>   
>   * [ ]  Create market
>     
>     * [ ]  Test with USDC
>   * [ ]  Add liquidity
>   * [ ]  Remove liquidity
>   * [ ]  Buy
>   * [ ]  Sell
>   * [ ]  Redeem
>     
>     * [ ]  Correct amounts
> * [ ]  Meta data
>   
>   * [ ]  Works as expected (proper title, description, image)
> * [ ]  Redeem
>   
>   * [ ]  Correct amount of shares to redeem
>     
>     * [ ]  Before and after resolving
>   * [ ]  Correct value of shares to redeem
>     
>     * [ ]  Before and after resolving
>   * [ ]  Redeeming works as expected
> * [ ]  xDai <> Dai bridge
>   
>   * [ ]  xDai => Dai batch claim works
> * [ ]  Unwrapping redeem positions
>   
>   * [ ]  Scalar compound market unwraps cDai to Dai when redeeming
>   * [ ]  wxDai unwrapped to xDai on redeem
