### ISSUE TITLE
Refactoring testing checklist

### ISSUE THREAD

**Issue by KadenZipfel** [protofire/omen-exchange#2145]
Just a basic, general testing checklist below. Comment suggestions for additional things to test and I will add here.

Copy/paste this checklist into a comment and check things off after you've tested them.

- [ ] Categorical markets
    - [ ] Create market
    - [ ] Buy
    - [ ] Sell
    - [ ] Deposit
    - [ ] Withdraw
    - [ ] Bond outcome
    - [ ] Redeem winnings
- [ ] Scalar markets
    - [ ] Create market
    - [ ] Buy
    - [ ] Sell
    - [ ] Deposit
    - [ ] Withdraw
    - [ ] Bond outcome
    - [ ] Redeem winnings
    - [ ] Position table works as expected
        - Correct payout/profit/loss
    - [ ] Market buy slider works as expected
        - Correct payout/profit/loss
- [ ] Account
    - [ ] Correct wallet balances
    - [ ] Correct omen account balances
- [ ] xDai relay
    - [ ] Deposit
    - [ ] Withdraw
- [ ] Mobile
    - Should just be relatively functional as per usual
